name: flutter_setup
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
#  intl:
  dio: ^5.4.3+1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  go_router: ^14.0.2
  get_it: ^7.7.0
  fluttertoast: ^8.2.5
  permission_handler: ^11.3.1
  dartx: ^1.2.0
  easy_localization: ^3.0.6
  pretty_dio_logger:
  logger: ^2.2.0
  wechat_assets_picker: ^9.0.3
  transparent_image: ^2.0.1
  internet_connection_checker: ^1.0.0+1
  fk_user_agent: ^2.1.0
  pull_to_refresh: ^2.0.0
  provider: ^6.1.2
  sqflite: ^2.3.3
  dart_pusher_channels: ^1.2.2+1
  record: ^5.0.5
  location: 5.0.3
  hexcolor: ^3.0.1
  flex_color_scheme: ^7.3.1
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  flutter_bloc: ^8.1.5


dependency_overrides:
#  photo_manager: ^3.0.0-dev.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  freezed: ^2.4.6

flutter_icons:
  image_path: 'assets/icons/app_icon.png'
  android: true
  background_color_android: "#1361b4"
  ios: false

flutter:
  uses-material-design: true
  assets:
    - languages/en-US.json
    - languages/my-MM.json
    - assets/images/
    - assets/icons/
    - assets/anims/
    - shorebird.yaml

  fonts:
    - family: notosan_mm
      fonts:
        - asset: fonts/notosan_mm.ttf
    - family: oleo
      fonts:
        - asset: fonts/oleo.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
