name: flutter_setup
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl:
  dio: ^5.4.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  go_router: ^13.0.1
  get_it: ^7.6.7
  fluttertoast: ^8.2.4
  permission_handler: ^11.1.0
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.3
  retrofit: ^4.0.3
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartx: ^1.2.0
  easy_localization: ^3.0.4
  pretty_dio_logger:
  logger: ^2.0.2+1
  wechat_assets_picker: ^9.0.0
  transparent_image: ^2.0.1
  internet_connection_checker: ^1.0.0+1
  fk_user_agent: ^2.1.0
  pull_to_refresh: ^2.0.0
  provider: ^6.1.1
  sqflite: ^2.3.2
  dart_pusher_channels: ^1.2.2
  record: ^5.0.4
  location: 5.0.3


dependency_overrides:
#  photo_manager: ^3.0.0-dev.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - languages/en-US.json
    - languages/my-MM.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
